Require active_support/time in test.rb
https://github.com/rails/rails/issues/37391

```
Failure/Error: 'Cache-Control' => "public, max-age=#{1.hour}"

NoMethodError:
  undefined method `hour' for 1:Integer

      'Cache-Control' => "public, max-age=#{1.hour}"
                                             ^^^^^
# ./spec/example_app/config/environments/test.rb:19:in `block in <main>'
```